[general]
import = ["keymap.toml", "theme.toml"]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 15

[colors]
transparent_background_colors = true

[window]
dynamic_padding = true
opacity = 0.85
blur = true
startup_mode = "Fullscreen"

[env]
TERM = "xterm-256color"

