vim.keymap.set({ "n", "v" }, "<Left>", function()
    vim.cmd('echo "Go left with \'h\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<Down>", function()
    vim.cmd('echo "Go down with \'j\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<Up>", function()
    vim.cmd('echo "Go up with \'k\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<Right>", function()
    vim.cmd('echo "Go right with \'l\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<S-Left>", function()
    vim.cmd('echo "Go to previous word with \'e\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<S-Down>", function()
    vim.cmd('echo "Go down a page with \'C-d\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<S-Up>", function()
    vim.cmd('echo "Go up a page with \'C-u\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<S-Right>", function()
    vim.cmd('echo "Go to next word with \'w\'"')
end, { desc = "Disabled" })
