vim.keymap.set("v", "<C-j>", ":m '>+1<CR>gv=gv", { desc = "Move selected text down" })
vim.keymap.set("v", "<C-k>", ":m '<-2<CR>gv=gv", { desc = "Move selected text up" })
vim.keymap.set("n", "L", "G$", { desc = "Last file's char" })
vim.keymap.set("n", "H", "gg0", { desc = "First files's char" })
vim.keymap.set("n", "<C-d>", "<C-d>zz", { desc = "Go up a page" })
vim.keymap.set("n", "<C-u>", "<C-u>zz", { desc = "Go down a page" })
vim.keymap.set("n", "n", "nzzzv", { desc = "Next match" })
vim.keymap.set("n", "N", "Nzzzv", { desc = "Previous match" })
vim.keymap.set("n", "<Esc>", "<cmd>noh<CR>", { desc = "Remove highlight" })
vim.keymap.set("x", "p", [["_dP]], { desc = "Substitute text" })
vim.keymap.set("t", "<Esc>", [[<C-\><C-n>]], { desc = "Unfocus from terminal" })

vim.keymap.set({ "n", "v" }, "<Left>", function()
    vim.cmd('echo "Go left with \'h\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<Down>", function()
    vim.cmd('echo "Go down with \'j\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<Up>", function()
    vim.cmd('echo "Go up with \'k\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<Right>", function()
    vim.cmd('echo "Go right with \'l\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<S-Left>", function()
    vim.cmd('echo "Go to previous word with \'e\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<S-Down>", function()
    vim.cmd('echo "Go down a page with \'C-d\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<S-Up>", function()
    vim.cmd('echo "Go up a page with \'C-u\'"')
end, { desc = "Disabled" })
vim.keymap.set({ "n", "v" }, "<S-Right>", function()
    vim.cmd('echo "Go to next word with \'w\'"')
end, { desc = "Disabled" })
