#!/bin/zsh

if [[ $# -eq 0 ]]; then
    echo "Missing command (up/down/status)"

elif [[ "$1" == "up" ]]; then
    read -s "key?Decryption key: "
    echo
    for file in ~/.env/*; do
        if [[ -f "$file" ]]; then
            env_name=$(basename "$file")
            content=$(openssl enc -aes-256-cbc -d -in "$file" -pass pass:"$key" -pbkdf2 -iter 10000 2>/dev/null)
            if [[ $? -ne 0 ]]; then
                echo "Wrong key!"
                return 1
            else
                export "$env_name"="$content"
            fi
        fi
    done
    export DOTENV_SET=1
    echo "~/.env variables set"

elif [[ "$1" == "down" ]]; then
    for file in ~/.env/*; do
        if [[ -f "$file" ]]; then
            env_name=$(basename "$file")
            unset "$env_name"
        fi
    done
    unset DOTENV_SET
    echo "~/.env variables unset"

elif [[ "$1" == "status" ]]; then
    if [[ -z "$DOTENV_SET" ]]; then
        echo dotenv is down
    else
        echo dotenv is up
    fi
fi
