#!/bin/bash

tomove_home=".bashami .clang-format .prettierrc .gitconfig .git-credentials .nanorc Scripts"
tomove_config="zed warp-terminal user-dirs.conf user-dirs.dirs"

home_dir="$HOME/"
config_dir="$HOME/.config/"

destination="$1"

echo "The following files and folders will be copied to $destination"
echo
echo "$home_dir: $tomove_home"
echo "$config_dir: $tomove_config"
echo
read -s -r -p "To proceed, insert password for $destination: " pw
echo

cd "$home_dir"
for item in $tomove_home; do
    sshpass -p "$pw" scp -r "$item" "$destination":"$home_dir"
done

cd "$config_dir"
for item in $tomove_config; do
    sshpass -p "$pw" scp -r "$item" "$destination":"$config_dir"
done

cd
echo
echo "Finish!"
